### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by ArsenShnurkov** [grokys/Avalonia#1]
is it old version of
https://github.com/Perspex/Perspex
?

**Comment by grokys** [comment]
Hi Arsen,

Yes, Avalonia was my attempt to write a cross-platform framework that
followed WPF's API exactly, however I wasn't enjoying myself having to
follow WPF's API because it quite frankly sucks in many places.

So I started Perspex which is similar but we're free to deviate from WPF's
API where we feel it makes sense.

Steven

**Comment by superlloyd** [comment]
Woa, you did it again! Gonna check the awesomess once again! :p
Too bad I can't replace mono-droid & mono-iOS with that!
